version: "3.8"

services:
    db-mysql:
        image: mysql:5.7
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: consumption_history'
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
        ports:
              - 3306:3306
        networks:
              - springboot-mysql-net

    consumption-history-app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
              SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/consumption_history?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
              SPRING_DATASOURCE_USERNAME: root
              SPRING_DATASOURCE_PASSWORD: secret
        depends_on:
            - db-mysql
        networks:
            - springboot-mysql-net

networks:
    springboot-mysql-net:
        driver: bridge