server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/consumption_history
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!@

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: create